server:
  port: 8002
spring:
  application:
    name: spring-cloud-comsumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#配置熔断器
feign:
  hystrix:
    enabled: true
